[workspace]
members = [
  "bin/pcl", 
  "crates/phoundry",
  "crates/common"
]
default-members = ["bin/pcl"]
resolver = '2'


[workspace.package]
version = "0.0.1"
authors = ["Phylax Systems"]
edition = "2021"
rust-version = "1.80"
license = "GPL-3.0-only"
repository = "https://github.com/phylaxsystems/pcl"
exclude = [".github/"]


[workspace.dependencies]
forge = { git = "https://github.com/phylaxsystems/phoundry.git", branch = "master" }
foundry_cli = { git = "https://github.com/phylaxsystems/phoundry.git", branch = "master" }
tokio = { version = "1.39.0", features = ["full"] }
clap = { version = "4.5.23", features = ["derive"] }
eyre = "0.6.12"