[package]
name = "pcl"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vergen = "9.0.2"
clap = "4.5.23"