# blatantly lifted from https://github.com/init4tech/actions/blob/main/.github/workflows/rust-base.yml
name: Rust

on:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: make format-check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: make lint-check

  release:
    needs: [fmt, lint]
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 60 # 60 minutes
    name: Create Release for ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Initialize Git submodules
        run: git submodule update --init --recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: ${{ matrix.target }}
          override: true
          components: rust-src
      - uses: Swatinem/rust-cache@v2

      # Install dependencies for Linux builds
      - name: Install Linux dependencies
        if: runner.os == 'Linux' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          # Install OpenSSL development libraries for aarch64
          sudo apt-get install -y libssl-dev pkg-config
          # For cross-compilation
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      # Build for all targets with static linking
      - name: Build Release
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          # For aarch64 Linux cross-compilation
          CC_aarch64_unknown_linux_gnu: ${{ matrix.target == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ matrix.target == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}
          # Force using vendored OpenSSL
          OPENSSL_NO_VENDOR: "0"
          OPENSSL_STATIC: "1"
          # Disable pkg-config for cross-compilation
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          # Explicitly add the target to be extra cautious
          rustup target add ${{ matrix.target }}

          # Build with static linking
          cargo build --release --target ${{ matrix.target }}

          # Extract architecture and OS from target
          arch=$(echo ${{ matrix.target }} | cut -d'-' -f1)
          os=$(echo ${{ matrix.target }} | cut -d'-' -f2)

          # Copy binaries with appropriate names
          cp target/${{ matrix.target }}/release/pcl pcl-$arch-$os
          cp target/${{ matrix.target }}/release/phorge phorge-$arch-$os || true

          # Check library dependencies (informational)
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "Library dependencies for pcl:"
            otool -L pcl-$arch-$os
            
            if [[ -f "phorge-$arch-$os" ]]; then
              echo "Library dependencies for phorge:"
              otool -L phorge-$arch-$os
            fi
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            echo "Library dependencies for pcl:"
            ldd pcl-$arch-$os || echo "No dynamic dependencies (static binary)"
            
            if [[ -f "phorge-$arch-$os" ]]; then
              echo "Library dependencies for phorge:"
              ldd phorge-$arch-$os || echo "No dynamic dependencies (static binary)"
            fi
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            pcl-*
            phorge-*
          draft: false
          prerelease: false
          generate_release_notes: true
